-- Tabela de pipelines de agentes
CREATE TABLE IF NOT EXISTS public.lab_agent_pipelines (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT,
  steps JSONB NOT NULL, -- [{order:1, agent_id:'uuid'}, {order:2, agent_id:'uuid'}]
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de logs de execução de pipelines
CREATE TABLE IF NOT EXISTS public.lab_pipeline_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pipeline_id UUID REFERENCES lab_agent_pipelines(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  input_messages JSONB,
  output_messages JSONB,
  steps_executed INTEGER,
  total_latency_ms INTEGER,
  total_cost_usd NUMERIC,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_lab_pipelines_active ON lab_agent_pipelines(active);
CREATE INDEX IF NOT EXISTS idx_lab_pipelines_created_at ON lab_agent_pipelines(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lab_pipeline_logs_pipeline_id ON lab_pipeline_logs(pipeline_id);
CREATE INDEX IF NOT EXISTS idx_lab_pipeline_logs_user_id ON lab_pipeline_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_lab_pipeline_logs_created_at ON lab_pipeline_logs(created_at DESC);

-- Função para atualizar updated_at
CREATE OR REPLACE FUNCTION update_lab_pipelines_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger para atualizar updated_at
DROP TRIGGER IF EXISTS update_lab_pipelines_timestamp_trigger ON lab_agent_pipelines;
CREATE TRIGGER update_lab_pipelines_timestamp_trigger
BEFORE UPDATE ON lab_agent_pipelines
FOR EACH ROW
EXECUTE FUNCTION update_lab_pipelines_timestamp();

-- RLS (Row Level Security)
ALTER TABLE lab_agent_pipelines ENABLE ROW LEVEL SECURITY;
ALTER TABLE lab_pipeline_logs ENABLE ROW LEVEL SECURITY;

-- Políticas RLS - Pipelines
DROP POLICY IF EXISTS "Anyone can view active pipelines" ON lab_agent_pipelines;
CREATE POLICY "Anyone can view active pipelines"
  ON lab_agent_pipelines
  FOR SELECT
  USING (active = true);

DROP POLICY IF EXISTS "Admins can view all pipelines" ON lab_agent_pipelines;
CREATE POLICY "Admins can view all pipelines"
  ON lab_agent_pipelines
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() 
      AND role IN ('admin', 'gestor_we')
    )
  );

DROP POLICY IF EXISTS "Admins can manage pipelines" ON lab_agent_pipelines;
CREATE POLICY "Admins can manage pipelines"
  ON lab_agent_pipelines
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() 
      AND role IN ('admin', 'gestor_we')
    )
  );

-- Políticas RLS - Logs
DROP POLICY IF EXISTS "Users can view their own pipeline logs" ON lab_pipeline_logs;
CREATE POLICY "Users can view their own pipeline logs"
  ON lab_pipeline_logs
  FOR SELECT
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Admins can view all pipeline logs" ON lab_pipeline_logs;
CREATE POLICY "Admins can view all pipeline logs"
  ON lab_pipeline_logs
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() 
      AND role IN ('admin', 'gestor_we')
    )
  );

DROP POLICY IF EXISTS "System can insert pipeline logs" ON lab_pipeline_logs;
CREATE POLICY "System can insert pipeline logs"
  ON lab_pipeline_logs
  FOR INSERT
  WITH CHECK (true);

-- Comentários
COMMENT ON TABLE lab_agent_pipelines IS 'Pipelines de agentes colaborativos';
COMMENT ON COLUMN lab_agent_pipelines.steps IS 'Array JSON de passos: [{order, agent_id}]';
COMMENT ON TABLE lab_pipeline_logs IS 'Logs de execução de pipelines';
COMMENT ON COLUMN lab_pipeline_logs.input_messages IS 'Mensagens de entrada no pipeline';
COMMENT ON COLUMN lab_pipeline_logs.output_messages IS 'Resultado final do pipeline';

-- Pipeline exemplo: Resumo → Revisão → Tradução
INSERT INTO lab_agent_pipelines (name, description, steps, active)
VALUES
  (
    'Pipeline: Resumo, Revisão e Tradução',
    'Pipeline completo: resume artigo, revisa linguagem e traduz para inglês',
    '[{"order":1,"agent_id":"Agente 1"},{"order":2,"agent_id":"Agente 2"},{"order":3,"agent_id":"Agente 3"}]'::jsonb,
    false
  );
