-- Tabela de memória de longo prazo (Memória Declarativa)
CREATE TABLE IF NOT EXISTS public.lab_agent_memory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  agent_id TEXT, -- null = memória global do usuário
  key TEXT NOT NULL,
  value TEXT NOT NULL,
  importance INTEGER DEFAULT 1 CHECK (importance >= 1 AND importance <= 5),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, agent_id, key)
);

-- Tabela de resumos de conversas (Memória Episódica)
CREATE TABLE IF NOT EXISTS public.lab_conversation_summaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id UUID REFERENCES lab_conversations(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  agent_id TEXT,
  summary TEXT NOT NULL,
  tokens_est INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_mem_user_agent ON lab_agent_memory(user_id, agent_id);
CREATE INDEX IF NOT EXISTS idx_mem_user_global ON lab_agent_memory(user_id) WHERE agent_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_mem_updated_at ON lab_agent_memory(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_sum_user_conv ON lab_conversation_summaries(user_id, conversation_id);
CREATE INDEX IF NOT EXISTS idx_sum_created_at ON lab_conversation_summaries(created_at DESC);

-- Função para atualizar updated_at
CREATE OR REPLACE FUNCTION update_lab_memory_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger para atualizar updated_at
DROP TRIGGER IF EXISTS update_lab_memory_timestamp_trigger ON lab_agent_memory;
CREATE TRIGGER update_lab_memory_timestamp_trigger
BEFORE UPDATE ON lab_agent_memory
FOR EACH ROW
EXECUTE FUNCTION update_lab_memory_timestamp();

-- RLS (Row Level Security)
ALTER TABLE lab_agent_memory ENABLE ROW LEVEL SECURITY;
ALTER TABLE lab_conversation_summaries ENABLE ROW LEVEL SECURITY;

-- Políticas RLS - Memória
DROP POLICY IF EXISTS "Users can view their own memories" ON lab_agent_memory;
CREATE POLICY "Users can view their own memories"
  ON lab_agent_memory
  FOR SELECT
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can manage their own memories" ON lab_agent_memory;
CREATE POLICY "Users can manage their own memories"
  ON lab_agent_memory
  FOR ALL
  USING (user_id = auth.uid());

-- Políticas RLS - Resumos
DROP POLICY IF EXISTS "Users can view their own summaries" ON lab_conversation_summaries;
CREATE POLICY "Users can view their own summaries"
  ON lab_conversation_summaries
  FOR SELECT
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "System can insert summaries" ON lab_conversation_summaries;
CREATE POLICY "System can insert summaries"
  ON lab_conversation_summaries
  FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS "Users can delete their own summaries" ON lab_conversation_summaries;
CREATE POLICY "Users can delete their own summaries"
  ON lab_conversation_summaries
  FOR DELETE
  USING (user_id = auth.uid());

-- Função para limpar resumos antigos (manter últimos N por conversa)
CREATE OR REPLACE FUNCTION cleanup_old_summaries()
RETURNS void AS $$
BEGIN
  DELETE FROM lab_conversation_summaries
  WHERE id NOT IN (
    SELECT id FROM (
      SELECT id, ROW_NUMBER() OVER (
        PARTITION BY conversation_id 
        ORDER BY created_at DESC
      ) as rn
      FROM lab_conversation_summaries
    ) ranked
    WHERE ranked.rn <= 5
  );
END;
$$ LANGUAGE plpgsql;

-- Comentários
COMMENT ON TABLE lab_agent_memory IS 'Memória de longo prazo dos agentes por usuário';
COMMENT ON COLUMN lab_agent_memory.agent_id IS 'null = memória global do usuário';
COMMENT ON COLUMN lab_agent_memory.importance IS 'Importância da memória (1-5)';
COMMENT ON TABLE lab_conversation_summaries IS 'Resumos de conversas para contexto episódico';
COMMENT ON COLUMN lab_conversation_summaries.summary IS 'Resumo comprimido da conversa';
COMMENT ON COLUMN lab_conversation_summaries.tokens_est IS 'Estimativa de tokens do resumo';
